### ISSUE TITLE
Improve default implementation of useXhr

### ISSUE THREAD

**Issue by Chris2m** [requirejs/text#106]
Currently the implementation of `text.useXhr` simply checks if the URL to be loaded is cross domain and disables xhr in case it is. This neglects the fact that [all modern browsers (IE10, Chrome, Firefox) and (IE8 and IE9) with some restrictions](http://caniuse.com/#search=CORS) support cross origin resource sharing.

Ways around this are using a custom override via requirejs.config as illustrated in the projects ReadMe. Alternatively, all plugin resources need to be optimized (`optimizeAllPluginResources: true`) which imposes an additional build step.

Therefore, I suggest to improve the default implementation by first checking if cors is supported:

```javascript 
// Adapted from: https://raw.github.com/Modernizr/Modernizr/master/feature-detects/cors.js
if (typeof XMLHttpRequest !== "undefined" && 'withCredentials' in new XMLHttpRequest()) {
   return true;
}
```

Additionally, support for IE8 and IE9 CORS could be added as shown at https://github.com/auchenberg/requirejs-text-cors. I am happy to create a pull request if it is of any help.

**Comment by jrburke** [comment]
The main issue is that it is not enough for the browser to support CORS, but the server needs to support it too, and the plugin does not have a way to know this without doing some sort of request. So it seemed the server capability needed to be told to the plugin in some way, which is the goal of the useXhr hook. It can be as simple as returning true from that function if it is true for a given app.

So going to close for now, given the requirement on knowing server capabilities. Feel free to continue discussion here though and we can reopen as needed.
