### ISSUE TITLE
jsEscape issue with Kendo MVVM Templates

### ISSUE THREAD

**Issue by taemon1337** [requirejs/text#107]
I was working on a Kendo UI MVVM application using require.js text templates.  Kendo MVVM templates embed JavaScript in data attributes (like in the example template below):

```
<div id="example-template">
  <div id="grid"
    data-role="grid"
    data-bind="dataSource"
    data-columns="[
         {
            title: 'Id',
            field: 'id',
         }
    ]"
  ></div>
</div>
```

When optimizing with r.js (v2.1.15) with the text plugin (v2.0.5+) the text plugin would error while trying to compress this template, like so:
```
Tracing dependencies for: main
toTransport skipping text!views/../../templates/example-template.html: Error: Line 1: Unexpected identifier
...
```

Upon further inspection, it is failing because any single quote inside the data-attributes is not escaped.

I don't know if this is an actual issue, or just an incompatibility with Kendo MVVM, but I was able to workaround this issue with the following technique.

1. I used double quotes everywhere in templates except when I needed to use single quotes (data-attributes).
2. Modified the text plugin's jsEscape function with the following:
```
jsEscape: function(content) {
   return content
     .replace(/'/g,"\\\'")  /* escapes any single quotes */
     ... /* and keep all the original replacers of course */
}
```

I couldn't find ANY reference to issues like this on google or github or anywhere, so not sure if this is just me, but this was the only way I could get it working and figured it might as least help someone else googling, assuming its not an actual issue.

**Comment by jrburke** [comment]
The latest text plugin is 2.0.14, and r.js is at 2.1.17, I tried an example project with a module that does a require for the example template above and the built completed without error. Does upgrading help? If not, then a more fleshed out example project with a build step that shows the error would help.

**Comment by taemon1337** [comment]
Thanks for checking it out.  I'm willing to bet this is not a text plugin issue, it may just be my setup and not an actual issue for any library.  I will close this now that it is at least documented.
