### ISSUE TITLE
xhr query (createXhr) in IE with "file:" prefix raises "access denied" error

### ISSUE THREAD

**Issue by srad** [requirejs/text#108]
The error occurs in line 270, in the current version:

```javascript
...
xhr.open('GET', url, true);
...
```

http://stackoverflow.com/questions/2142156/read-file-urls-in-ie-xmlhttprequest/2753160#2753160

jQuery works fine, can't you just copy+paste their module, they have one only for xhr.

This fixes the issue:

```javascript
createXhr: return new ActiveXObject("MSXML2.XMLHTTP");
```

This is the issue: http://stackoverflow.com/questions/2142156/read-file-urls-in-ie-xmlhttprequest

I'm actually a little surprised, to say the least, why you risk to create these long solved issue by creating an own xhr function.

**Comment by srad** [comment]
I recommending to override the createXhr function in the require config, to return the jquery xhr object, which always works:

```javascript
require.config({
    config:  {
        text: {
            createXhr: function () {
                return $.ajaxSettings.xhr();
            }
        }
    },
   ...
});
```

**Comment by jrburke** [comment]
That is a good tip, thanks for sharing it. This seems to be an IE7/IE8 even issue, and while it is unfortunate, those browsers are fading away, and I would prefer to not maintain that kind of code for a fix natively in this repo. It seems perfectly valid though for other to provide a text plugin with this awareness, and it can even be added to the [Plugins page](https://github.com/jrburke/requirejs/wiki/Plugins).

Going to close as a discussion ticket, feel free to continue discussion here though.

**Comment by srad** [comment]
Notice that this wasn't an ancient IE, it's IE 11 on Win 8.1
