### ISSUE TITLE
NuGet package is out of date

### ISSUE THREAD

**Issue by unicron** [requirejs/text#110]
The most recent available version is 2.0.7

**Comment by jrburke** [comment]
If this is from https://www.nuget.org/packages/RequireJS.Text/ I do not control that entry in NuGet. It would best to contact the owner of that entry to get the update.

Closing for now, but feel free to continue discussion here and we can reopen if we discover something that can be done by this repo.

**Comment by unicron** [comment]
Understood, thanks.  I have already attempted to contact the owner of that package.  I guess we will wait and see.
