### ISSUE TITLE
When baseUrl is a full url, it apends '.js' to the file path

### ISSUE THREAD

**Issue by micahblu** [requirejs/text#111]

**Comment by micahblu** [comment]
I have a fullpath baseUrl and a simple require:
```js
var template = require('text!./main-navigation.html');`
```

Which produces a GET request for `http://.../main-navigation.html.js`

**Comment by micahblu** [comment]
Appears to be only happening in localhost

**Comment by micahblu** [comment]
I believe the problem is that I'm using a remote CDN url for the baseUrl causing the plugin to default to a jsonp request instead of xhr. Any ideas on how to work around this?

**Comment by jrburke** [comment]
The useXhr config option allows customizing when it tries for a .js vs using an XHR request. Details here:
https://github.com/requirejs/text#xhr-restrictions

**Comment by hyingreborn** [comment]
@micahblu Do you know how to configure it?I don't know how to configure...this is my code:
```
require.config({
   // other config
   config: {
        text: {
            useXhr: function (url, protocol, hostname, port) {
               return true
            }
        }
    }
});
```
@jrburke  it doesn't work...
