### ISSUE TITLE
Success callback to pass xhr instead of responseText

### ISSUE THREAD

**Issue by fahimfarookme** [requirejs/text#118]
For the success callback - it would be useful for some users to gain access to xhr object (instead of xhr.responseText) to find out more information about the actual response.

`callback(xhr);`

at line 300

**Comment by jrburke** [comment]
The goal of this loader plugin is to define a module whose value is the text of the module, and if the xhr succeeds, then it is considered defined as the text.

So no plans for this feature. There are some [xhr hooks](https://github.com/requirejs/text#custom-xhr-hooks) that you can define to maybe wrap the native XHR call, or just listen to finished calls via the `onXhrComplete` that could give you a more global look at what status codes are returned.

However if the desire is to get the XHR object as the module value or more customized manipulation of the result, it might be best to make a new, different plugin.
