### ISSUE TITLE
Dynamic template path

### ISSUE THREAD

**Issue by bkirankumars** [requirejs/text#126]
My requirement is like configuring the template path dynamically,we have parent directory and child directory .Each time when I hit the web server the child directory templates are loaded by default. If we don't have that template in child it should fetch from Parent ,Is there any way to implement it using require js .Please suggest.

**Comment by jrburke** [comment]
It is not really designed to do fetches that may fail. There is a [paths fallbacks feature](http://requirejs.org/docs/api.html#pathsfallbacks) for requirejs, but it is not a generic mechanism, and best to only use for a few resources.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by bkirankumars** [comment]
Thank you
