### ISSUE TITLE
Do we have a provision to omit extention like (".html) in text.js

### ISSUE THREAD

**Issue by venkateshnadar8** [requirejs/text#135]
I am using text.js to load lots of html file so just thinking do we have any way around to exclude extension. I checked it in source file. There is no easy way around so I went on creating a normalize method in text.js which check for config if any default extension is set then normalize the resource name accordingly or else it is default to ".html". 

`
normalize: function (name, normalize) {
            var _ext = masterConfig.defaultExt || ".html";

            if (name.match(/!strip/gi) && name.match(/\.[a-z]+!strip/gi)) {
                return name;
            } else if(name.match(/!strip/gi)){
                name = name.replace(/!strip/gi, _ext + "!strip");
            } else if (!name.match(/[a-z]+\.[a-z]+/gi)) {
                name = name + _ext;
            }

            return name;
        },
`

and in requirejs config like this 

`
require.config(
  config:{
    text:{
      defaultExt:".tpl"
    }
  }
})
`

Please tell me if there is any easy way around so I don't need to touch the core file.

**Comment by jrburke** [comment]
There are no other options at this time. It should be fine to create a fork of this plugin and change it to the behavior your prefer. This plugin is not really changing any more, and if you create a fork, it will likely be able to merge upstream changes into it later if things do change.

Closing as no plans to modify the current behavior, variations on this plugin code as forks is encouraged.
