### ISSUE TITLE
Load timeout for modules: text!filename.html_unnormalized2_unnormalized6

### ISSUE THREAD

**Issue by dey-dey** [requirejs/text#16]
Uncaught Error: Load timeout for modules: text!Template.File1.html_unnormalized2_unnormalized6, text!Template.File2.html_unnormalized3_unnormalized7

http://requirejs.org/docs/errors.html#timeout require.js:192
makeError require.js:192
checkLoaded require.js:754
(anonymous function)

For a long time in development where our files aren't built (we're loading around 451), we get above error. File1 and File2 are the first templates in the stack being called.

This is an intermittent error that fluctuates in frequency.

I can't quite pin it on text except that it only errors out on the html files being loaded with text plugin every time.

I apologize if I've missed this in resolved issues with Require or text plugin.

**Comment by nini-web** [comment]
hello , i set it , but, it always tell me timeout.
require.config({
			urlArgs: "bust=" +  (new Date()).getTime(),
			paths:{
				'text':'/testcloud/common/js/text',
				'dialogTpl':'/testcloud/common/template/dialog/dialog.html'
			}
		});
it is right ?

**Comment by nini-web** [comment]
sorry ,i got it.
