### ISSUE TITLE
Uncaught Error: Script error for: text

### ISSUE THREAD

**Issue by stevenvachon** [requirejs/text#51]
I get the above error in Chrome. I get this error in Safari:
"TypeError: 'undefined' is not an object (evaluating 'e.normalize')"

Here is the code causing the problem:

`require(["scripts/text.js", "text!templates/template.html"], function()
{
    console.log(arguments);
});`

Even without the `console.log` line, it still breaks. I've tried loading the `text!` after text.js has loaded, and it made no difference.

**Comment by mfoonirlee** [comment]
I think you should include text plugins for requirejs to solve this problem.

**Comment by hubbertj** [comment]
Yes I dont see want text.js isn't just a part of requireJS
