### ISSUE TITLE
Make it work with HTTP-Caching

### ISSUE THREAD

**Issue by fab1an** [requirejs/text#65]
https://blog.httpwatch.com/2009/08/07/ajax-caching-two-important-facts/

**Comment by rwhepburn** [comment]
FYI: I had a similar issue in IE 11 where .html files requested through the text plugin were only being cached for the session. Clicking the browser Refresh button would cause .html files requested by RequireJS's text plugin that I would expect to be in the browser cache to be requested again.

From what I could tell, the XMLHTTPRequest object was ignoring the cache headers. The only fix I found was the following:
```
text.onXhr = function (xhr) { xhr.msCaching = "enabled"; }
```
