### ISSUE TITLE
Create a bower.json file

### ISSUE THREAD

**Issue by rafaellyra** [requirejs/text#93]
I think we can add a bower.json file to set the main file and works fine with bower-installer:
https://www.npmjs.org/package/bower-installer

**Comment by mindmelting** [comment]
Could do with a bower.json in order for gulp/grunt plugins such as https://github.com/ck86/main-bower-files to work out of the box, without having to include overrides.

**Comment by jbblanchet** [comment]
+1 for main-bower-files compatibility.

**Comment by Zizaco** [comment]
+1

**Comment by jrburke** [comment]
If someone does a pull request with a bower.json that works, then I will merge it. I prefer to keep the JSON as small as possible, so any optional fields should not be included. I want to minimizes the number of metadata I need to update. Ideally, just "main" is enough, but whatever minimum valid JSON value would be fine.

**Comment by rafaellyra** [comment]
https://github.com/requirejs/text/pull/100 :+1:
